apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/hello-geely:latest
          ports:
            - containerPort: 8080
