apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: example
          image: docker.io/alanfan/hello-geely:latest
          ports:
            - containerPort: 8080
